version: '3.9'

services:
  # Frontend (React) service
  frontend:
    build:
      context: ./financial-health-calculator  # Path to your React app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map the container's port to the host machine

  # Backend (Node.js) service
  backend:
    build:
      context: ./backend  # Path to your Node.js app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map the container's port to the host machine
    depends_on:
      - frontend  # Ensure the frontend service is ready before starting the backend service

