name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set working directory
        run: cd ../financial-health-calculator

      - name: Install dependencies
        run: npm install

      - name: Build and test frontend
        run: npm run build
        working-directory: ./financial-health-calculator  # Path to your React app

      - name: Build and test backend
        run: npm test
        working-directory: ./backend  # Path to your Node.js app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v2

      - name: Build and push Docker images
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker-compose build
          docker-compose push

      - name: Deploy to production
        run: docker-compose up -d
