name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get -y install docker-compose

    - name: Build and Run Docker Compose
      run: |
        docker-compose up -d

    - name: Tear Down Docker Compose
      run: docker-compose down
